# .goreleaser.yml
version: 2

project_name: cloud-easy-connector

builds:
- id: cloud-easy-connector
  main: ./cmd/main
  binary: cloud-easy-connector
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  - arm

release:
  name_template: "Release {{ .Tag }}"
  github:
    owner: raywall
    name: cloud-easy-connector

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - 'Merge pull request'
    - 'Merge branch'
