name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Go Version
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.1

      - name: Create Release
        run: |
          go get -u github.com/goreleaser/goreleaser
          goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}